import { Response, NextFunction } from "express";
import { User } from "../models/User";
import { generateBuyerToken } from "../utils/jwt";
import { AuthRequest } from "../middlewares/auth";

// GET /api/buyers (admin only) — list all buyers
export async function getBuyers(req: AuthRequest, res: Response, next: NextFunction) {
  try {
    const buyers = await User.find({ role: "buyer" }).select("-password").sort({ createdAt: -1 });
    return res.status(200).json({ success: true, data: buyers });
  } catch (err) {
    next(err);
  }
}

// GET /api/buyers/:id (admin only) — buyer detail + activity log
export async function getBuyerById(req: AuthRequest, res: Response, next: NextFunction) {
  try {
    const buyer = await User.findOne({ _id: req.params.id, role: "buyer" }).select("-password");
    if (!buyer) {
      return res.status(404).json({ success: false, message: "Buyer not found" });
    }
    return res.status(200).json({ success: true, data: buyer });
  } catch (err) {
    next(err);
  }
}

// PATCH /api/buyers/:id/regenerate-token (admin only)
export async function regenerateBuyerToken(req: AuthRequest, res: Response, next: NextFunction) {
  try {
    const buyer = await User.findOne({ _id: req.params.id, role: "buyer" });
    if (!buyer) {
      return res.status(404).json({ success: false, message: "Buyer not found" });
    }

    buyer.buyerToken = generateBuyerToken();
    buyer.activityLogs.push({
      action: "token-regenerated",
      detail: `Regenerated by admin (${req.user?.username})`,
      at: new Date()
    });
    await buyer.save();

    return res.status(200).json({
      success: true,
      message: "Buyer token regenerated",
      data: { buyerToken: buyer.buyerToken }
    });
  } catch (err) {
    next(err);
  }
}

// PATCH /api/buyers/:id/toggle-active (admin only)
export async function toggleBuyerActive(req: AuthRequest, res: Response, next: NextFunction) {
  try {
    const buyer = await User.findOne({ _id: req.params.id, role: "buyer" });
    if (!buyer) {
      return res.status(404).json({ success: false, message: "Buyer not found" });
    }

    buyer.isActive = !buyer.isActive;
    buyer.activityLogs.push({
      action: buyer.isActive ? "activated" : "deactivated",
      detail: `By admin (${req.user?.username})`,
      at: new Date()
    });
    await buyer.save();

    return res.status(200).json({
      success: true,
      message: `Buyer ${buyer.isActive ? "diaktifkan" : "dinonaktifkan"}`,
      data: { isActive: buyer.isActive }
    });
  } catch (err) {
    next(err);
  }
}

// DELETE /api/buyers/:id (admin only)
export async function deleteBuyer(req: AuthRequest, res: Response, next: NextFunction) {
  try {
    const buyer = await User.findOneAndDelete({ _id: req.params.id, role: "buyer" });
    if (!buyer) {
      return res.status(404).json({ success: false, message: "Buyer not found" });
    }
    return res.status(200).json({ success: true, message: "Buyer deleted" });
  } catch (err) {
    next(err);
  }
}

// PATCH /api/buyers/:id/license (admin only) — atur status & tanggal expired lisensi
export async function updateBuyerLicense(req: AuthRequest, res: Response, next: NextFunction) {
  try {
    const { licenseStatus, licenseExpiresAt } = req.body;

    const buyer = await User.findOne({ _id: req.params.id, role: "buyer" });
    if (!buyer) {
      return res.status(404).json({ success: false, message: "Buyer not found" });
    }

    if (licenseStatus !== undefined) buyer.licenseStatus = licenseStatus;
    if (licenseExpiresAt !== undefined) {
      buyer.licenseExpiresAt = licenseExpiresAt ? new Date(licenseExpiresAt) : null;
    }

    buyer.activityLogs.push({
      action: "license-updated",
      detail: `By admin (${req.user?.username}) -> ${buyer.licenseStatus}`,
      at: new Date()
    });
    await buyer.save();

    return res.status(200).json({
      success: true,
      message: "Lisensi diperbarui",
      data: { licenseStatus: buyer.licenseStatus, licenseExpiresAt: buyer.licenseExpiresAt }
    });
  } catch (err) {
    next(err);
  }
}
